name: 发布

on:
  push:
    branches: ['main']

permissions:
  packages: write
  contents: write

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}

    name: 发布

    runs-on: ubuntu-latest
    steps:
      - name: 检查
        uses: actions/checkout@v3
        with:
          ref: main

      - name: 构建
        run: |
          npm run build

      - name: 创建新发布
        uses: elgohr/Github-Release-Action@v5
        with:
          title: ${{ github.event.head_commit.message }}
